-- Gravity Media (SB4 — Josh Rosen) — 30 Broadcast Production Prospect Seeds
-- All warmth_score = 50 (neutral baseline), source = 'ai_generated_seed_v1'
-- Mix of US, UK, and Australian companies across broadcast production segments
-- Does NOT include Gravity Media's own subsidiaries
--
-- Run after the Session 12 migration so SB4 tenant exists.
-- Usage: Insert via Supabase SQL editor or psql, substituting the SB4 tenant UUID.

-- Get SB4 tenant ID
DO $$
DECLARE
  sb4_id UUID;
BEGIN
  SELECT id INTO sb4_id FROM public.tenants WHERE slug = 'josh-rosen-gravity-media';
  IF sb4_id IS NULL THEN
    RAISE EXCEPTION 'SB4 tenant (josh-rosen-gravity-media) not found. Run Session 12 migration first.';
  END IF;

  -- Insert 30 broadcast production prospects
  INSERT INTO public.prospects (tenant_id, ref_id, dodge_number, name, type, value, value_display, stage, stage_detail, city, state, owner, gc, pain_points, primary_pain_point, suggested_service, warmth_score, source) VALUES
  -- OB/Remote Production (6)
  (sb4_id, 'bcast-001', 'GM-OB-001', 'NEP Group', 'OB/Remote Production', 5000000, '$5M', 'prospecting', 'Initial Research', 'Pittsburgh', 'PA', 'NEP Group', 'NFL / ESPN', '["aging OB fleet replacement","remote production transition","IP infrastructure upgrade"]'::jsonb, 'Remote production transition', 'Remote production consulting', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-002', 'GM-OB-002', 'Game Creek Video', 'OB/Remote Production', 3000000, '$3M', 'prospecting', 'Initial Research', 'Hudson', 'NH', 'Game Creek Video', 'Fox Sports / CBS', '["crew scheduling across events","4K/HDR truck upgrades","multi-camera IP workflow"]'::jsonb, '4K/HDR truck upgrades', 'OB truck integration', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-003', 'GM-OB-003', 'DSNG Worldwide', 'OB/Remote Production', 1500000, '$1.5M', 'prospecting', 'Initial Research', 'Burbank', 'CA', 'DSNG Worldwide', 'Various Networks', '["satellite uplink modernization","remote gallery workflow","cloud production hybrid"]'::jsonb, 'Cloud production hybrid', 'Remote production systems', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-004', 'GM-OB-004', 'Timeline Television', 'OB/Remote Production', 2500000, '$2.5M', 'prospecting', 'Initial Research', 'London', 'UK', 'Timeline Television', 'BBC / Sky Sports', '["UHD mobile unit deployment","at-home production workflow","bonded cellular backup"]'::jsonb, 'At-home production workflow', 'Remote production consulting', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-005', 'GM-OB-005', 'Cloudbass', 'OB/Remote Production', 1000000, '$1M', 'prospecting', 'Initial Research', 'Maidenhead', 'UK', 'Cloudbass', 'Premier League / BT Sport', '["flypack design optimization","crew management at scale","remote commentary integration"]'::jsonb, 'Flypack design optimization', 'Flypack design services', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-006', 'GM-OB-006', 'Global Production Services', 'OB/Remote Production', 2000000, '$2M', 'prospecting', 'Initial Research', 'Sydney', 'NSW', 'GPS Australia', 'Cricket Australia / NRL', '["multi-venue coordination","regional OB coverage gaps","talent management platform"]'::jsonb, 'Multi-venue coordination', 'Multi-venue OB solutions', 50, 'ai_generated_seed_v1'),

  -- Sports Broadcast (6)
  (sb4_id, 'bcast-007', 'GM-SP-001', 'IMG Productions', 'Sports Broadcast', 8000000, '$8M', 'prospecting', 'Initial Research', 'London', 'UK', 'IMG / Endeavor', 'Wimbledon / ATP Tour', '["global rights distribution","multi-platform delivery","archive digitization"]'::jsonb, 'Multi-platform delivery', 'End-to-end production', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-008', 'GM-SP-002', 'Whistle Sports', 'Sports Broadcast', 2000000, '$2M', 'prospecting', 'Initial Research', 'New York', 'NY', 'Whistle', 'Social-first sports content', '["short-form production scaling","multi-platform simultaneous delivery","creator network management"]'::jsonb, 'Short-form production scaling', 'Digital content production', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-009', 'GM-SP-003', 'Sunset+Vine', 'Sports Broadcast', 3000000, '$3M', 'prospecting', 'Initial Research', 'London', 'UK', 'Sunset+Vine / Tinopolis', 'World Athletics / UCI', '["live event turnaround speed","multi-language commentary","highlight clipping automation"]'::jsonb, 'Live event turnaround speed', 'Live production services', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-010', 'GM-SP-004', 'Fox Sports Australia', 'Sports Broadcast', 6000000, '$6M', 'prospecting', 'Initial Research', 'Sydney', 'NSW', 'Foxtel Group', 'AFL / NRL / Cricket', '["studio automation","remote commentary workflow","cloud-based replay system"]'::jsonb, 'Studio automation', 'Studio systems integration', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-011', 'GM-SP-005', 'Deltatre', 'Sports Broadcast', 4000000, '$4M', 'prospecting', 'Initial Research', 'Turin', 'IT', 'Deltatre / Bain Capital', 'FIFA / UEFA / Olympics', '["OTT platform reliability","real-time stats integration","second screen experience"]'::jsonb, 'OTT platform reliability', 'Streaming infrastructure', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-012', 'GM-SP-006', 'ESPN Production Operations', 'Sports Broadcast', 10000000, '$10M', 'prospecting', 'Initial Research', 'Bristol', 'CT', 'Walt Disney / ESPN', 'MNF / College GameDay / UFC', '["remote production at scale","talent studio upgrades","mobile production unit refresh"]'::jsonb, 'Remote production at scale', 'Large-scale remote production', 50, 'ai_generated_seed_v1'),

  -- Live Event Production (6)
  (sb4_id, 'bcast-013', 'GM-EV-001', 'Done and Dusted', 'Live Event Production', 3500000, '$3.5M', 'prospecting', 'Initial Research', 'London', 'UK', 'Done and Dusted', 'Grammy Awards / MTV VMAs', '["awards show technical complexity","live-to-tape transitions","AR/VR integration for live shows"]'::jsonb, 'Awards show technical complexity', 'Live event production', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-014', 'GM-EV-002', 'Silent House Productions', 'Live Event Production', 2000000, '$2M', 'prospecting', 'Initial Research', 'Nashville', 'TN', 'Silent House', 'CMA Awards / iHeartRadio', '["multi-camera music show production","in-ear monitoring integration","live streaming hybrid events"]'::jsonb, 'Multi-camera music show production', 'Live music production', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-015', 'GM-EV-003', 'LiveU', 'Live Event Production', 4000000, '$4M', 'prospecting', 'Initial Research', 'Hackensack', 'NJ', 'LiveU', 'News / Sports / Events', '["bonded cellular reliability in dense venues","5G integration","multi-camera cellular production"]'::jsonb, 'Bonded cellular reliability', 'Cellular broadcast solutions', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-016', 'GM-EV-004', 'Screencraft', 'Live Event Production', 1500000, '$1.5M', 'prospecting', 'Initial Research', 'Melbourne', 'VIC', 'Screencraft', 'Australian Open / Melbourne Cup', '["outdoor broadcast in extreme weather","rapid setup for multi-day events","fibre infrastructure for venues"]'::jsonb, 'Rapid setup for multi-day events', 'Event broadcast services', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-017', 'GM-EV-005', 'Banijay Sports & Events', 'Live Event Production', 5000000, '$5M', 'prospecting', 'Initial Research', 'Amsterdam', 'NL', 'Banijay Group', 'Tour de France / Dakar Rally', '["global event coordination","multi-time-zone production","sustainable broadcast operations"]'::jsonb, 'Global event coordination', 'Global production management', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-018', 'GM-EV-006', 'CTV Outside Broadcasts', 'Live Event Production', 2500000, '$2.5M', 'prospecting', 'Initial Research', 'London', 'UK', 'CTV OB', 'Premier League / Rugby', '["HDR consistency across venues","RF camera coordination","mobile unit fleet management"]'::jsonb, 'HDR consistency across venues', 'HDR broadcast services', 50, 'ai_generated_seed_v1'),

  -- Graphics/Virtual Studio (6)
  (sb4_id, 'bcast-019', 'GM-GR-001', 'Vizrt Group', 'Graphics/Virtual Studio', 6000000, '$6M', 'prospecting', 'Initial Research', 'Bergen', 'NO', 'Vizrt', 'NDI / TriCaster / Viz Engine', '["real-time graphics engine upgrades","virtual set adoption resistance","operator training at scale"]'::jsonb, 'Virtual set adoption', 'Virtual studio consulting', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-020', 'GM-GR-002', 'Zero Density', 'Graphics/Virtual Studio', 3000000, '$3M', 'prospecting', 'Initial Research', 'Ankara', 'TR', 'Zero Density', 'Reality Engine clients', '["Unreal Engine integration complexity","tracking system calibration","talent training for virtual sets"]'::jsonb, 'Unreal Engine integration', 'Virtual production services', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-021', 'GM-GR-003', 'Ross Video', 'Graphics/Virtual Studio', 4000000, '$4M', 'prospecting', 'Initial Research', 'Ottawa', 'ON', 'Ross Video', 'XPression / Voyager', '["production switcher lifecycle","graphics workflow automation","cloud rendering adoption"]'::jsonb, 'Production switcher lifecycle', 'Broadcast systems integration', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-022', 'GM-GR-004', 'Brainstorm Multimedia', 'Graphics/Virtual Studio', 1500000, '$1.5M', 'prospecting', 'Initial Research', 'Madrid', 'ES', 'Brainstorm', 'InfinitySet clients', '["AR graphics for live broadcast","election graphics automation","multi-language graphics templates"]'::jsonb, 'AR graphics for live broadcast', 'AR broadcast solutions', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-023', 'GM-GR-005', 'Disguise', 'Graphics/Virtual Studio', 5000000, '$5M', 'prospecting', 'Initial Research', 'London', 'UK', 'Disguise', 'LED volume productions', '["xR stage design","media server infrastructure","real-time rendering pipeline"]'::jsonb, 'xR stage design', 'xR production services', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-024', 'GM-GR-006', 'Mo-Sys Engineering', 'Graphics/Virtual Studio', 2000000, '$2M', 'prospecting', 'Initial Research', 'London', 'UK', 'Mo-Sys', 'StarTracker clients', '["camera tracking accuracy","virtual production workflow","talent compositing in real-time"]'::jsonb, 'Camera tracking accuracy', 'Camera tracking systems', 50, 'ai_generated_seed_v1'),

  -- Streaming/Digital Delivery (6)
  (sb4_id, 'bcast-025', 'GM-SD-001', 'Endeavor Streaming', 'Streaming/Digital Delivery', 4000000, '$4M', 'prospecting', 'Initial Research', 'New York', 'NY', 'Endeavor', 'DAZN / PFL / UFC', '["low-latency live streaming","global CDN optimization","DRM implementation complexity"]'::jsonb, 'Low-latency live streaming', 'Streaming infrastructure', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-026', 'GM-SD-002', 'Grabyo', 'Streaming/Digital Delivery', 2000000, '$2M', 'prospecting', 'Initial Research', 'London', 'UK', 'Grabyo', 'Premier League / La Liga clubs', '["real-time clipping workflow","social media distribution speed","multi-platform publishing"]'::jsonb, 'Real-time clipping workflow', 'Digital clipping platform', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-027', 'GM-SD-003', 'Kiswe Mobile', 'Streaming/Digital Delivery', 3000000, '$3M', 'prospecting', 'Initial Research', 'Bridgewater', 'NJ', 'Kiswe', 'BTS / K-pop / eSports', '["interactive fan experience","multi-view streaming","virtual fan participation"]'::jsonb, 'Interactive fan experience', 'Interactive streaming', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-028', 'GM-SD-004', 'Telstra Broadcast Services', 'Streaming/Digital Delivery', 7000000, '$7M', 'prospecting', 'Initial Research', 'Melbourne', 'VIC', 'Telstra', 'AFL / NRL / Cricket Australia', '["satellite-to-IP transition","regional distribution complexity","cloud playout migration"]'::jsonb, 'Satellite-to-IP transition', 'IP distribution consulting', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-029', 'GM-SD-005', 'Wurl (AppLovin)', 'Streaming/Digital Delivery', 3500000, '$3.5M', 'prospecting', 'Initial Research', 'Palo Alto', 'CA', 'AppLovin / Wurl', 'FAST channel operators', '["FAST channel monetization","content aggregation automation","ad insertion quality"]'::jsonb, 'FAST channel monetization', 'FAST channel services', 50, 'ai_generated_seed_v1'),
  (sb4_id, 'bcast-030', 'GM-SD-006', 'Red Bee Media', 'Streaming/Digital Delivery', 5000000, '$5M', 'prospecting', 'Initial Research', 'London', 'UK', 'Ericsson / Red Bee', 'BBC / Channel 4 / SVT', '["playout modernization","media management at scale","disaster recovery for live channels"]'::jsonb, 'Playout modernization', 'Playout infrastructure', 50, 'ai_generated_seed_v1');

END $$;
