-- Deal Room Artifacts table
-- Stores structured documents (deal summaries, competitive analyses, meeting preps)
-- generated by Claude from uploaded sources.

CREATE TABLE IF NOT EXISTS deal_room_artifacts (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id     UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  deal_room_id  UUID NOT NULL REFERENCES deal_rooms(id) ON DELETE CASCADE,
  artifact_type TEXT NOT NULL CHECK (artifact_type IN ('deal_summary', 'competitive_analysis', 'meeting_prep')),
  title         TEXT NOT NULL DEFAULT '',
  content       JSONB,
  status        TEXT NOT NULL DEFAULT 'generating' CHECK (status IN ('generating', 'ready', 'error')),
  sources_used  JSONB DEFAULT '[]'::jsonb,
  error_message TEXT,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_deal_room_artifacts_tenant
  ON deal_room_artifacts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_deal_room_artifacts_room
  ON deal_room_artifacts(tenant_id, deal_room_id);

-- RLS
ALTER TABLE deal_room_artifacts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access on deal_room_artifacts"
  ON deal_room_artifacts FOR ALL
  USING (true)
  WITH CHECK (true);

-- updated_at trigger
CREATE OR REPLACE TRIGGER set_updated_at_deal_room_artifacts
  BEFORE UPDATE ON deal_room_artifacts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
